"""Embedding service — store and retrieve embeddings (V2).

Handles serialization/deserialization of embedding vectors for
KnowledgeItems and GameplayEvents. Embeddings are generated by
Ollama (nomic-embed-text) and stored as BLOBs in separate tables.

See ARCHITECTURE_V2.md §7.2 (KnowledgeItem embeddings) and §8.1
(GameplayEvent embeddings).
"""

from __future__ import annotations

import struct
from typing import Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from gpcg.config import get_settings
from gpcg.core.models import KnowledgeItem, KnowledgeItemEmbedding
from gpcg.domains.games.models import GameplayEventEmbedding
from gpcg.infrastructure.llm import LLMClient, LLMError
from gpcg.logging import get_logger

log = get_logger(__name__)

EMBEDDING_MODEL = "nomic-embed-text"


# ── Serialization ─────────────────────────────────────────────────────────────


def serialize_embedding(vector: list[float]) -> bytes:
    """Serialize a float list to bytes (float32 array)."""
    return struct.pack(f"{len(vector)}f", *vector)


def deserialize_embedding(data: bytes) -> list[float]:
    """Deserialize bytes back to a float list (float32 array)."""
    if not data:
        return []
    count = len(data) // 4  # 4 bytes per float32
    return list(struct.unpack(f"{count}f", data))


# ── KnowledgeItem Embeddings ──────────────────────────────────────────────────


def store_knowledge_item_embedding(
    session: Session,
    item_id: int,
    vector: list[float],
    *,
    model: str = EMBEDDING_MODEL,
) -> None:
    """Store or update the embedding for a KnowledgeItem."""
    existing = session.get(KnowledgeItemEmbedding, item_id)
    if existing:
        existing.embedding = serialize_embedding(vector)
        existing.model = model
    else:
        emb = KnowledgeItemEmbedding(
            item_id=item_id,
            embedding=serialize_embedding(vector),
            model=model,
        )
        session.add(emb)
    session.flush()


def get_knowledge_item_embedding(session: Session, item_id: int) -> Optional[list[float]]:
    """Retrieve the embedding vector for a KnowledgeItem."""
    emb = session.get(KnowledgeItemEmbedding, item_id)
    if not emb or not emb.embedding:
        return None
    return deserialize_embedding(emb.embedding)


def generate_and_store_knowledge_item_embedding(
    session: Session,
    item_id: int,
    llm: LLMClient,
) -> bool:
    """Generate an embedding for a KnowledgeItem via Ollama and store it.

    Returns True on success, False on failure.
    """
    item = session.get(KnowledgeItem, item_id)
    if not item:
        log.error(f"Cannot embed KnowledgeItem #{item_id}: not found")
        return False

    # Combine title + content for embedding
    text = f"{item.title}\n{item.content[:500]}"
    try:
        vector = llm.embed(text, model=EMBEDDING_MODEL)
        if not vector:
            log.warning(f"Empty embedding for KnowledgeItem #{item_id}")
            return False
        store_knowledge_item_embedding(session, item_id, vector)
        log.info(f"Stored embedding for KnowledgeItem #{item_id} (dim={len(vector)})")
        return True
    except (LLMError, Exception) as e:
        log.warning(f"Embedding generation failed for KnowledgeItem #{item_id}: {e}")
        return False


# ── GameplayEvent Embeddings ──────────────────────────────────────────────────


def store_gameplay_event_embedding(
    session: Session,
    event_id: int,
    vector: list[float],
    *,
    model: str = EMBEDDING_MODEL,
) -> None:
    """Store or update the embedding for a GameplayEvent."""
    existing = session.get(GameplayEventEmbedding, event_id)
    if existing:
        existing.embedding = serialize_embedding(vector)
        existing.model = model
    else:
        emb = GameplayEventEmbedding(
            event_id=event_id,
            embedding=serialize_embedding(vector),
            model=model,
        )
        session.add(emb)
    session.flush()


def get_gameplay_event_embedding(session: Session, event_id: int) -> Optional[list[float]]:
    """Retrieve the embedding vector for a GameplayEvent."""
    emb = session.get(GameplayEventEmbedding, event_id)
    if not emb or not emb.embedding:
        return None
    return deserialize_embedding(emb.embedding)


def generate_and_store_gameplay_event_embedding(
    session: Session,
    event_id: int,
    text: str,
    llm: LLMClient,
) -> bool:
    """Generate an embedding for a GameplayEvent via Ollama and store it.

    The text is the event description (from VLM analysis).

    Returns True on success, False on failure.
    """
    try:
        vector = llm.embed(text, model=EMBEDDING_MODEL)
        if not vector:
            log.warning(f"Empty embedding for GameplayEvent #{event_id}")
            return False
        store_gameplay_event_embedding(session, event_id, vector)
        log.info(f"Stored embedding for GameplayEvent #{event_id} (dim={len(vector)})")
        return True
    except (LLMError, Exception) as e:
        log.warning(f"Embedding generation failed for GameplayEvent #{event_id}: {e}")
        return False


# ── Similarity ────────────────────────────────────────────────────────────────


def cosine_similarity(a: list[float], b: list[float]) -> float:
    """Compute cosine similarity between two vectors."""
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(y * y for y in b) ** 0.5
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)
